site_name: Text Forge Docs
site_url: https://text-forge.github.com/docs
repo_url: https://github.com/text-forge/docs
repo_name: GitHub
edit_uri: blob/Main/docs

site_description: Online documentation for Text Forge
site_author: Text Forge
copyright: MIT License | Copyright (c) 2025 Mahan Khalili and contributors

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Setup:
      - Main: setup.md
      - Test: index.md
  - Modes: modes.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - gdscript
  prev_next_buttons_location: both
extra_ccs:
  - style.css

draft_docs: drafts/